apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: calculatorgrpc
  namespace: calculatorgrpc
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - calculatorgrpc.teste.com.br
    port:
      name: calculatorgrpc-grpc-5000
      number: 5000
      protocol: GRPC
  - hosts:
    - calculatorgrpc.teste.com.br
    port:
      name: calculatorgrpc-https-443
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-system/calculatorgrpc-cert-ingress